# Generated by Django 4.1.3 on 2022-11-21 05:17

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_bio_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=profiles.models.image_filename),
        ),
    ]
