# Generated by Django 4.1.3 on 2022-11-22 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matched',
            field=models.ManyToManyField(related_name='matched', to=settings.AUTH_USER_MODEL),
        ),
    ]
