# Generated by Django 4.1.3 on 2022-11-22 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_matched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='matched',
        ),
    ]
