# Generated by Django 4.1.3 on 2022-11-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_profile_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_dated',
            field=models.BooleanField(default=False),
        ),
    ]
