# Generated by Django 4.1.3 on 2022-11-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winks',
            name='is_wink_backed',
            field=models.BooleanField(default=False),
        ),
    ]
