# Generated by Django 4.1.3 on 2022-11-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_date_coupon_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date_schedule',
            new_name='date_scheduled',
        ),
    ]
