# Generated by Django 4.1.3 on 2022-12-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_alter_match_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('type', models.CharField(choices=[('RESERVATION', 'Reservation'), ('FLIGHT', 'Flight')], default='RESERVATION', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='date',
            name='coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.coupon'),
        ),
    ]
