name: Deploy to Prod

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1                    # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: 044232640434.dkr.ecr.us-east-1.amazonaws.com/gng5300-dating-app       
                                              # set this to your Amazon ECR repository name
  ECS_SERVICE: dating-app-prod  # set this to your Amazon ECS service name
  ECS_CLUSTER: dating-app  # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: dating-app-task
                                              # set this to the path to your Amazon ECS task definition
                                              # file, e.g. .aws/task-definition.json

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Deploy Amazon ECS task definition
      id: deploy-task
      run: |
        aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment --region $AWS_REGION
