name: Build Image

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    steps:
    - name: Build and image
      uses: docker/build-push-action@v2.10.0
      with:
        context: ${{ env.GITHUB_WORKSPACE }}
        file: ${{ env.GITHUB_WORKSPACE }}/Dockerfile
        push: false
